[package]
name = "wos-bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitch-irc = "3.0.1"
itertools = "0.10.1"
tokio = { version = "1.10.0", features = ["full"] }
dotenv = "0.15.0"
